# Generated by Django 4.2.11 on 2026-07-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0007_alter_currencysettings_international_delivery_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Mid Year Preorder Sales', max_length=120)),
                ('badge_text', models.CharField(blank=True, default='PREORDER SALE', max_length=80)),
                ('headline', models.CharField(blank=True, default='Bringing factory prices to your doorstep', max_length=160)),
                ('offer_website', models.CharField(blank=True, default='30% OFF WEBSITE ORDERS', max_length=80)),
                ('offer_whatsapp', models.CharField(blank=True, default='20% OFF WHATSAPP ORDERS', max_length=80)),
                ('offer_extra', models.CharField(blank=True, default='FREE GIFT WRAP', max_length=80)),
                ('marquee_text', models.TextField(default='JBLuxe Accessories presents Mid Year Preorder Sales — bringing factory prices to your doorstep with 30% off website orders, 20% off WhatsApp orders, and free gift wrap. Running July 20th – 25th, 2026. Please read our Terms of Service before ordering.', help_text='Continuous scrolling announcement text shown on the homepage banner.')),
                ('megaphone_image', models.ImageField(blank=True, help_text='Optional megaphone / shout graphic (left side on desktop).', null=True, upload_to='announcements/')),
                ('poster_image', models.ImageField(blank=True, help_text='Optional sale poster graphic (right side / mobile hero).', null=True, upload_to='announcements/')),
                ('cta_label', models.CharField(blank=True, default='Shop Preorder Looks', max_length=60)),
                ('cta_url', models.CharField(blank=True, default='/shop', max_length=255)),
                ('start_date', models.DateField(blank=True, help_text='Sale start date (e.g. July 20, 2026)', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Sale end date (e.g. July 25, 2026)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first when several are active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sale announcement',
                'verbose_name_plural': 'Sale announcements',
                'ordering': ['order', '-updated_at'],
            },
        ),
    ]
